name: pipeline CI

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

   
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
        
    - name: Install NPM
      run: npm install
    - name: Install Mocha
      run: npm i -g mocha
    - name: Run Unit Tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "SoftUni Username ---> captain76"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API }}

    
